### ISSUE TITLE
Panic on jwks well-known url GET

### ISSUE THREAD

**Issue by owmo-dev** [auth0-blog/go-react-vr#2]
The `http.Get` method in my `getPemCert` function is producing a panic when I attempt to test this locally. I've copy / pasted the **Identifer** from the API Settings on Auth0 and formatted the URl as directed in the blog post (I've changed it in the code block below for privacy). Am I missing something?

https://github.com/auth0-blog/go-react-vr/blob/master/main.go#L123

```
/usr/local/go/src/net/http/server.go:2969 +0x36c
2020/11/24 13:25:46 http: panic serving [::1]:57013: Get "https://tutorial.mydomain.com/.well-known/jwks.json": dial tcp: lookup tutorial.metastash.io: no such host
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000096000)
/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x12eecc0, 0xc0000ac2f0)
/usr/local/go/src/runtime/panic.go:975 +0x47a
main.main.func1(0xc0000e0000, 0xc0000bc007, 0x32e, 0x13ba140, 0xc000092240)
/Users/grantmoore3d/go/src/github.com/grantmoore3d/tutorial-auth0-go-react/main.go:69 +0x21f
github.com/dgrijalva/jwt-go.(*Parser).ParseWithClaims(0xc0000dd748, 0xc0000bc007, 0x32e, 0x13ba140, 0xc000092240, 0x136f0a0, 0x12a025b, 0xc0000a4768, 0x100cc1b)
/Users/grantmoore3d/go/pkg/mod/github.com/dgrijalva/jwt-go@v3.2.0+incompatible/parser.go:51 +0x16d
github.com/dgrijalva/jwt-go.(*Parser).Parse(...)
/Users/grantmoore3d/go/pkg/mod/github.com/dgrijalva/jwt-go@v3.2.0+incompatible/parser.go:20
github.com/dgrijalva/jwt-go.Parse(0xc0000bc007, 0x32e, 0x136f0a0, 0x0, 0x0, 0x0)
/Users/grantmoore3d/go/pkg/mod/github.com/dgrijalva/jwt-go@v3.2.0+incompatible/token.go:89 +0x85
github.com/auth0/go-jwt-middleware.(*JWTMiddleware).CheckJWT(0xc00006c140, 0x13bea80, 0xc0000c4000, 0xc0000b2200, 0x134b2a0, 0xc00010adc0)
/Users/grantmoore3d/go/pkg/mod/github.com/auth0/go-jwt-middleware@v0.0.0-20201030150249-d783b5c46b39/jwtmiddleware.go:204 +0x225
github.com/auth0/go-jwt-middleware.(*JWTMiddleware).Handler.func1(0x13bea80, 0xc0000c4000, 0xc0000b2200)
/Users/grantmoore3d/go/pkg/mod/github.com/auth0/go-jwt-middleware@v0.0.0-20201030150249-d783b5c46b39/jwtmiddleware.go:111 +0x5e
net/http.HandlerFunc.ServeHTTP(0xc00000e460, 0x13bea80, 0xc0000c4000, 0xc0000b2200)
/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00013e000, 0x13bea80, 0xc0000c4000, 0xc0000b2000)
/Users/grantmoore3d/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x13bea80, 0xc0000c4000, 0xc0000b2000)
/Users/grantmoore3d/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc00000e6a0, 0x13bea80, 0xc0000c4000, 0xc0000b2000)
/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc000152000, 0x13bea80, 0xc0000c4000, 0xc0000b2000)
/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000096000, 0x13bf000, 0xc0000aa000)
/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2969 +0x36c
^Csignal: interrupt
```

**Comment by owmo-dev** [comment]
I figured it out, I was accidentally copying the Audience and not the Auth0 URL. Stupid mistake!
